title: Nighthawk-Pages
description: "August 2023 to June 2024"
owner_name: Ryan Nguyen
github_username: ryann96
github_repo: "Team-Project"
baseurl: "/Team-Project"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/ryann96/Team-Project"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
